name: audio_bless
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  #ui
  font_awesome_flutter:
  flutter_spinkit:
  lottie:

  # firebase
  firebase_core:
  firebase_auth:
  google_sign_in:


  # audio management
  permission_handler:
  just_audio:
  file_picker:
  path_provider:

  # state management
  provider:
  bloc:
  flutter_bloc:
  equatable:

  # cache
  hive:
  hive_flutter:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  build_runner:
  hive_generator:


flutter:


  uses-material-design: true

  assets:
    - assets/
    - lotties/




